In [6]:
# Numpy
# this library let's us use matrices, vectors, and tensors. 

import numpy as np

A = np.ones([4,5,8])
print(A.shape)
print(A)

B = np.zeros([7])
print(B.shape)

(4, 5, 8)
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]
(7,)


In [10]:
# let's load the Iris dataset

from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target

print('The shape of X is: ', X.shape)
print('The shape of y is: ', y.shape)
print(type(X))
print(type(y))

The shape of X is:  (150, 4)
The shape of y is:  (150,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [16]:
# data splitting for cross validation

NtotalDatapoints = X.shape[0]
if X.shape[0] == y.shape[0]:
  print('The dimensions of the data and the labels match!')
NtotalFeatures = X.shape[1]

# we want to split the data into training and test sets
test_percent = 10
NtestDatapoints = int(NtotalDatapoints / test_percent)

# numpy has this very handy function to generate random numbers in a range, without replacement
test_indices = np.random.choice(NtotalDatapoints, size=NtestDatapoints, replace=False)
print(test_indices)
print(len(test_indices))

The dimensions of the data and the labels match!
[ 82 133 143  92 111 147  37 138 104  90  72  69  83  62  68]
15


In [20]:
# now let's split training and testing data

X_test = X[test_indices]
y_test = y[test_indices]
X_train = np.delete(X, test_indices, axis=0)
y_train = np.delete(y, test_indices)

print('The shape of X_train is: ', X_train.shape)
print('The shape of y_train is: ', y_train.shape)
print('The shape of X_test is: ', X_test.shape)
print('The shape of y_test is: ', y_test.shape)


The shape of X_train is:  (135, 4)
The shape of y_train is:  (135,)
The shape of X_test is:  (15, 4)
The shape of y_test is:  (15,)


In [ ]:
# split the training data into k-folds

N_k_folds = 5


